version: '3.7'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'PASS!123'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - /my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/my-db"
